<% if File.exist?('rubocop_common.yml') %>
inherit_from:
  - rubocop_common.yml
  - .rubocop_todo.yml
<% else %>
inherit_gem:
  rggen-devtools: config/rubocop_common.yml

inherit_from:
  - .rubocop_todo.yml
<% end %>

Metrics/ParameterLists:
  Exclude:
    - lib/rggen/core/input_base/yaml_loader.rb

Naming/AccessorMethodName:
  Exclude:
    - lib/rggen/core/input_base/yaml_loader.rb

Naming/MethodName:
  Exclude:
    - lib/rggen/core/core_extensions/kernel.rb

Style/SymbolProc:
  Exclude:
    - lib/rggen/core/input_base/component_factory.rb
