require 'facets/array/merge'
require 'facets/file/ext'
require 'facets/hash/symbolize_keys'
require 'facets/module/attr_setter'
require 'facets/pathname/to_path'
require 'facets/string/variablize'
require 'facets/symbol/variablize'
