config_version = "0"

exclude_patterns = [
  "**/.github/**",
  "**/spec/**"
]

test_patterns = [
  "**/spec/**"
]

[[source]]
name = "default"
default = true

[smells]
mode = "comment"

[[plugin]]
name = "rubocop"
version = "1.64.0"

[[plugin.fetch]]
url = "https://raw.githubusercontent.com/rggen/rggen-devtools/master/config/rubocop_common.yml"
path = "rubocop_common.yml"
