#!/usr/bin/env ruby
# frozen_string_literal: true

$LOAD_PATH.unshift(File.expand_path('../lib', __dir__))
require 'rggen/core'
require 'facets/module/lastname'

begin
  cli = RgGen::Core::CLI.new
  cli.run(ARGV)
rescue OptionParser::ParseError, RgGen::Core::RuntimeError => e
  abort "[#{e.class.lastname}] #{e.message}"
end
